apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-dszdvmnd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/dotnet-basic-dszdvmnd:cc2d149d01446ebae7c62c4e15be7fc47212e853@sha256:c1e7757008526948446d4de102a3e5e35cbf33fdbf29fd94ab4823b471599199
          name: container-image
